### ISSUE TITLE
does not work ie11

### ISSUE THREAD

**Issue by beans9** [chalk/ansi-regex#17]
It does not work on ie11.
It can be used after modifying the arrow function to a general function.

index.js
`
module.exports = () => {
	const pattern = [
		'[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[a-zA-Z\\d]*)*)?\\u0007)',
		'(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PRZcf-ntqry=><~]))'
	].join('|');
	return new RegExp(pattern, 'g');
};
`

modified..
`
module.exports = function () {
	const pattern = [
		'[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[a-zA-Z\\d]*)*)?\\u0007)',
		'(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PRZcf-ntqry=><~]))'
	].join('|');
	return new RegExp(pattern, 'g');
};
`

**Comment by sindresorhus** [comment]
https://github.com/chalk/strip-ansi/issues/18#issuecomment-358269027
