### ISSUE TITLE
IE problem

### ISSUE THREAD

**Issue by yukinight** [chalk/ansi-regex#18]
There is compatibility problem when I update the latest version, maybe the 'index.js' need to be transferred from ES6 to ES5

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
