### ISSUE TITLE
escape codes from `ansi-escapes` not being stripped by `strip-ansi`?

### ISSUE THREAD

**Issue by derhuerst** [chalk/ansi-regex#19]
Hey, thanks for this useful tool!

If I understand correctly, the following escape codes should be stripped by `strip-ansi`, right?

```js
const esc = require('ansi-escapes')
const stripAnsi = require('strip-ansi')

esc.scrollDown // '\u001b[T'
stripAnsi(esc.scrollDown) // '\u001b[T'
esc.beep // '\u0007'
stripAnsi(esc.beep) // '\u0007'
```

`clearScreen` gets stripped though:

```js
esc.clearScreen // '\u001bc'
stripAnsi(esc.clearScreen) // ''
```

**Comment by Qix-** [comment]
Beep won't. scrollDown should. Let me look :)

**Comment by Qix-** [comment]
#20 fixes this - good catch :)

**Comment by Qix-** [comment]
To be clear, beep isn't actually an escape code. It's considered a valid ASCII character that has nothing to do with escapes and the like. It'd be out of scope for this module.

**Comment by derhuerst** [comment]
> To be clear, beep isn't actually an escape code. It's considered a valid ASCII character that has nothing to do with escapes and the like. It'd be out of scope for this module.

Yeah, makes sense now that I look at it again.

> #20 fixes this - good catch :)

Cool!
