### ISSUE TITLE
Allowing regex to match only first

### ISSUE THREAD

**Issue by ZSkycat** [chalk/ansi-regex#23]
When I only need to find the first one, I don't need `g` flag.

scenes to be used: https://github.com/ZSkycat/ghost-progress-webpack-plugin/blob/master/src/helper.ts#L80

**Comment by sindresorhus** [comment]
Sounds like a valid use-case. I don't think it should accept regex flags though, but rather an option called `onlyFirst` to match only the first item.

**Comment by ZSkycat** [comment]
Agree, I will modify my commit
