### ISSUE TITLE
developmemt

### ISSUE THREAD

**Issue by houzhitaohzt** [chalk/ansi-regex#27]
![image](https://user-images.githubusercontent.com/20673060/52828889-996a7880-3105-11e9-8839-5500a9594fde.png)

**Comment by Qix-** [comment]
If you need to use this in the browser, you need to package it to do so. ANSI doesn't do much in the browser normally, not sure why you'd need it there.

**Comment by houzhitaohzt** [comment]
> If you need to use this in the browser, you need to package it to do so. ANSI doesn't do much in the browser normally, not sure why you'd need it there.

This component is installed with the webpack-cli installation package. In the development environment, this code will not be compiled by Babel, and the compiled code will show the arrow function, which cannot be opened in ie (the production environment has not been tested yet).

**Comment by Qix-** [comment]
Why are you running webpack-cli in the browser?
