### ISSUE TITLE
Does not work on terminal-link

### ISSUE THREAD

**Issue by LitoMore** [chalk/ansi-regex#28]
This bug only appears on `iTerm 2`.

### How to reproduce

```javascript
const terminalLink = require('terminal-link');
const stripAnsi = require('strip-ansi');

const link = terminalLink('click', 'https://github.com', {fallback: text => text});

console.log(stripAnsi(link));
```

### Expected ouput

```
click
```

### Actual output

```
ttps://github.com/sindresorhusclick
```

**Comment by LitoMore** [comment]
@sindresorhus What about the case if the terminal does not support terminal link?

Should we add the terminal link pattern to the patterns array?

**Comment by sindresorhus** [comment]
Yes, it should strip no matter what. The string to strip might come from somewhere else where the terminal did support a terminal link.
