### ISSUE TITLE
Tests break (tsd)

### ISSUE THREAD

**Issue by Qix-** [chalk/ansi-regex#39]
@sindresorhus do you know why the tests are failing? Getting strange output with `tsd` that I've not seen before - have you faced it in other projects?

https://github.com/chalk/ansi-regex/runs/3600873607

**Comment by sindresorhus** [comment]
That `tsd` version bundles an old version of TypeScript, but the `@node/types` are hoisted from `globby` which is a dependency of `xo` and `ava` and it has a looser dependency, so it started using newer TS syntax which breaks here. Doesn't matter though. This is just a back port. No point in spending time on it.
