### ISSUE TITLE
React [CRA] - Don't work with 5.0.1

### ISSUE THREAD

**Issue by semihraifgurel** [chalk/ansi-regex#48]
```
/usr/local/bin/node /Users/user/.yarn/bin/yarn.js run start
**yarn run v1.22.15**
$ react-scripts start
/Users/user/project/node_modules/renderkid/node_modules/strip-ansi/index.js:2
var ansiRegex = require('ansi-regex')();
                ^
```
Only works with version 2.0.0 without errors and vulnerabilities.

**Comment by sindresorhus** [comment]
This is not the place to ask for CRA support. This package works fine in Node.js.

https://github.com/facebook/create-react-app/discussions

**Comment by shadyueh** [comment]
My project was with about 30 moderate vulnerabilities @semihraifgurel 
This solved my problem:
https://github.com/chalk/ansi-regex/issues/43#issuecomment-942601678
Keep `"ansi-regex": "^5.0.1"` in package.json.
I'm working with CRA also. Now everything is  ok:
<img width="413" alt="yarn-audit" src="https://user-images.githubusercontent.com/325680/145724899-9bcd2c25-3e08-43b3-a9bb-022894670ae7.png">
AND the app is running, cause i got 0 vulnerabilities before but got errors on running it.
