### ISSUE TITLE
Difference between stripAnsi and Node core

### ISSUE THREAD

**Issue by SBoudrias** [chalk/ansi-regex#5]
Looks like Node updated their ansi regex to also match VT control characters https://github.com/nodejs/io.js/blob/master/lib/readline.js#L974-L980

Should we do the same here?

**Comment by Qix-** [comment]
Not sure if we're including them as it stands, or not. Can you get a list of them?

**Comment by Qix-** [comment]
I looked over their regex again and nothing stands out that shows theirs supports any more than this one does. In fact, ours seems to support more (namely, CSI isn't always `\x1b` - theirs doesn't account for that).

Going to close this unless there is something I missed :) Thanks for the heads up!

**Comment by sindresorhus** [comment]
@Qix- Could you open an issue on Node.js about `(namely, CSI isn't always \x1b - theirs doesn't account for that).`?

**Comment by Qix-** [comment]
:+1:
