### ISSUE TITLE
【正则匹配不全】

### ISSUE THREAD

**Issue by enjoy-myLife** [chalk/ansi-regex#52]
[31;1m 失败 nums: 1 [m
[32;1m 成功 nums: 1 [m

好像没办法匹配到

**Comment by Qix-** [comment]
您好，这里没有足够的信息来帮助您。 另外，我们只说英语。 如果您仍然认为这是我们的代码的问题，请用英语打开一个新问题，并提供尽可能详细的信息。 谢谢！
