### ISSUE TITLE
Unable to match links ended with `\u001B` rather than `\u0007`.

### ISSUE THREAD

**Issue by RedYetiDev** [chalk/ansi-regex#56]
`ansi-regex` cannot match link regexes that end in `\u0001B`, as the regex only allows `\u0007`.

Example: `\x1b]8;;http://example.com/\x1b\\This is a link\x1b]8;;\x1b\\ hello`
Reference: https://github.com/nodejs/node/issues/53697

**Comment by hildjj** [comment]
For anyone digging into this, "OSC" is an "Operating System Command".  One reference I've found is from [Microsoft](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#window-title), which claims:

> As OSC sequences, they are ended with a String Terminator represented as <ST> and 
> transmitted with ESC \ (0x1B 0x5C). BEL (0x7) may be used instead as the terminator, 
> but the longer form is preferred.

So the bug should probably read "cannot match link regexes that end in \u0001B\u005c".

I've verified that iTerm2 at least does accept the sample string, so this isn't *just* a Microsoft thing.

**Comment by llimllib** [comment]
[wiki says](https://en.wikipedia.org/wiki/ANSI_escape_code#OSC) that `0x9C` and `0x1B 0x5C` (ESC \) are both standard STs and should be supported; I wish there were a real spec but it seems like practice is all we have here.

The [OSC8 spec](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) uses `0x1B 0x5C`, for whatever that's worth.
